"""The Makera Z1 and Makera Studio: machine limits, origins, and the G-code every job here writes the same way.

Jobs are written in the dialect Studio exports (;@MKR| header, T1 M6, M7, G28/M02
end), so Studio previews them and lists their tool like its own.
"""

import math
from pathlib import Path

MAX_FEED = 1200       # Z1 limits from Studio's machine table
MAX_RPM = 13000
SAFE_Z = 15.0         # Retract height, same as Studio's exports
APPROACH = 3.0        # Rapid down to this far above Z0 (or the top) before plunging
LEAD = 2.0            # Tool edge clearance past the edges of the stock
FLUTE_LENGTH = 12     # Header only, shown in Studio's tool list, unless --tool gives one
PROBE_FAST = 500      # Studio's Z probe: fast down to the touch, back off, then slow
PROBE_SLOW = 100
PROBE_SECONDS = 30.0  # Rough time for the tool change and Studio-style Z probe
PROBE_FEED = 300      # Grid probing feed, and the probe rod's way down beside a side
STUDIO_LOGS = Path.home() / "Library/Application Support/MakeraStudio/logs"  # macOS; the scripts take --log elsewhere

# Origin corner -> its position in stock coordinates, as fractions of the stock's size from front-left
ORIGINS = {
    "topFrontLeft": (0.0, 0.0),
    "topFrontRight": (1.0, 0.0),
    "topBackLeft": (0.0, 1.0),
    "topBackRight": (1.0, 1.0),
    "topCenter": (0.5, 0.5),
}


def fmt(value):
    s = f"{value:.3f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def to_program(origin, width, length, points):
    """Stock coordinates (from the front-left corner) -> program coordinates for the origin corner."""
    ox, oy = ORIGINS[origin]
    return [(u - ox * width, t - oy * length) for u, t in points]


def z_probe(x, y, fast=PROBE_FAST, g91=False):
    """Touch (x, y) the way Studio's own Z probe does, from the top of Z travel, and set Z0 there.

    Only G54 Z is touched (one EEPROM write). G92 is left alone: Studio's "set
    current position as origin" and its 4th-axis toolpaths keep X/Y/Z/A origins
    there. g91 writes G91 before the first G38.2 (see probe-stock's probe_job).
    """
    return [
        "G53 G0 Z-3",
        f"G90 G0 X{fmt(x)} Y{fmt(y)}",
        f"{'G91 ' if g91 else ''}G38.2 Z-108 F{fast}",
        "G91 G0 Z1",
        f"G38.2 Z-2 F{PROBE_SLOW}",
        "G10 L20 P0 Z0",
        "G90",
    ]


def start(cam, stock, origin, tool_dia, seconds, notes, g54_z=None, probe=(), flute_length=FLUTE_LENGTH):
    """A cutting job up to the cutter (T1) going in: Studio's header, our notes, then the probe lines if any.

    stock is (width, length, thickness). With g54_z the job prints G54 to Studio's
    log first, so the run can be stopped if Z0 isn't where the job was written for.
    """
    w, l, h = stock
    ox, oy = ORIGINS[origin]
    d, flutes = fmt(tool_dia), fmt(flute_length)
    return [
        ";@MKR|BEGIN",
        ";@MKR|SCHEMA|v=1.0.0",
        ";@MKR|MACHINE|id=Z1|name=Makera Z1",
        # Copied from a Studio export, for its preview only; whatever --material is, as the uuids
        # of Studio's other materials aren't known and which fields Studio needs is untested
        ";@MKR|MATERIAL|id=|name3=other|name1=Aluminum Alloys|name2=6061 Aluminum|uuid1=019bfadc-e599-74ef-b4ba-f34413e6f231",
        f";@MKR|STOCK|id=cuboid|length={fmt(w)}|width={fmt(l)}|height={fmt(h)}|diameter=50",
        f";@MKR|ORIGIN|id=0|type_name={origin}|x={fmt((ox - 0.5) * w)}|y={fmt((oy - 0.5) * l)}|z={fmt(h / 2)}",
        f";@MKR|CAM|id={cam}|name={cam}.py|v=1.0.0",
        ";@MKR|UNIT|value=mm",
        f";@MKR|MAXFEEDRATE|value={MAX_FEED}",
        f";@MKR|TOOL|number=1|id=|name={d}mm Flat End|type=Flat End|handlediameter={d}|sticklength=0"
        f"|shoulderlength={flutes}|flutelength={flutes}|diameter={d}|tipdiameter={d}"
        "|cornerradius=0|angle=0|halfAngle=0",
        f";@MKR|TIME|seconds={round(seconds)}",
        f";@MKR|TOOLPATH|number=1|tool_number=1|name=[T1]{cam.replace('-', ' ').title()}",
        ";@MKR|END",
        "",
        f"; Generated by {cam}.py (github.com/blackveilprecision/z1-macros) - edit the script, not this file.",
        *notes,
        "",
        "G90 G21",
        ";@MKR|TOOLPATH_START|toolpath_number=1",
        "",
        "M370 ; clear any auto-leveling grid left from an earlier job",
        *([f"M498 ; G54 Z should read {g54_z:.3f}: stop the job if not"] if g54_z is not None else []),
        "",
        *probe,
        f"; T1-{d}mm Flat End",
        "",
        "T1 M6",
        "M7",
    ]


def spindle_on(x, y, rpm, safe_z, approach_z):
    """To the first point, start the spindle, and come down to approach_z."""
    return [f"G0 X{fmt(x)} Y{fmt(y)}", f"S{rpm} M3", f"G0 Z{fmt(safe_z)}", f"G0 Z{fmt(approach_z)}"]


def cut(z, z_prev, pts, plunge_feed, feed, seconds):
    """Plunge from z_prev to z (off the stock) and feed along pts: (lines, seconds with this added).

    The time is added move by move, so ;@MKR|TIME rounds the same in every macro.
    """
    lines = [f"G1 Z{fmt(z)} F{plunge_feed}"]
    seconds += abs(z_prev - z) / plunge_feed * 60
    f = f" F{feed}"
    for (x0, y0), (x1, y1) in zip(pts, pts[1:]):
        words = (f"X{fmt(x1)}" if x1 != x0 else "") + (f" Y{fmt(y1)}" if y1 != y0 else "")
        lines.append(f"G1 {words.strip()}{f}")
        seconds += math.hypot(x1 - x0, y1 - y0) / feed * 60
        f = ""
    return lines, seconds


def face(path, zs, rpm, approach_z, plunge_feed, feed, seconds):
    """Spindle on, path at each of zs, every other one backwards, then the end: (lines, seconds with this added)."""
    lines = spindle_on(*path[0], rpm, SAFE_Z, approach_z)
    z_prev = approach_z
    for n, z in enumerate(zs, 1):
        pts = path if n % 2 else path[::-1]  # serpentine: each level starts where the last ended
        lines.append(f"; Level {n}/{len(zs)} Z{fmt(z)}")
        level, seconds = cut(z, z_prev, pts, plunge_feed, feed, seconds)
        lines += level
        z_prev = z
    return lines + end(SAFE_Z), seconds


def end(safe_z):
    """Up, coolant and spindle off, home, end of program."""
    return [f"G0 Z{fmt(safe_z)}", "M9", "M05", "G28", "M02"]
